-o demo/20-demo
-cs neukumivanov
-invert 1
-title Plot with inverted colour
-p source=%sample%/Pickering.scc,psym=fo
-p type=poisson,range=[.2,.7],isochron=1
-p range=[2,5],colour=violet,offset_age=[2,-3]