-o demo/00-demo
-cs neukumivanov
-ep mars
-ef trask
-title Differential plot with Poisson age evaluations,|equilibrium function, and epoch system
-p source=%sample%/Pickering.scc
-p type=poisson,range=[2,5],offset_age=[2,-2]
-p range=[.2,.7]