-o demo/04-demo
-title Cumulative fit with resurfacing correction|showing all corrected data points
-pr cumul
-cs neukumivanov
-p source=%sample%/Pickering.scc,psym=sq
-p type=c-fit,range=[.2,.7],resurf=1,psym=fsq,resurf_showall=1