-o demo/05-demo
-title Cumulative fits showing resurfacing correction|and fitted isochrons
-pr cumul
-cs neukumivanov
-p source=%sample%/Pickering.scc,psym=sq
-p type=c-fit,range=[2,5],isochron=1
-p range=[.2,.7],resurf=1,psym=fsq