-o demo/19-demo
-title Cumulative plot|with no binning
-pr cumul
-cs neukumivanov
-p source=%sample%/Pickering.scc,binning=none,psym=point
-p type=poisson,colour=red,range=[.22,.43],isochron=1
-p range=[2,5],colour=blue,offset_age=[2,-2]