-o demo/27-demo
-title Bin overlay to aid diameter selection|(normally remove before publication)
-cs neukumivanov
-p source=%sample%/Pickering.scc,binning=pseudo-log
-p type=poisson,range=[.26,.63]
--bins