name: Build Binaries for Multiple Platforms

on:
  push:
    tags:
      - 'v*'  # on any tag push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]  # ubuntu-latest, macos-latest,

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller craterstats.spec

      - name: Zip binary
        run: |
          # get version number from git tag (e.g., 'v3.3.3' -> '3.3.3')
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
      
#          if [ "${{ runner.os }}" == "Windows" ]; then
          ZIP_NAME="craterstats-$VERSION-win.zip"
          powershell -Command "Compress-Archive -Path dist\\craterstats -DestinationPath dist\\$ZIP_NAME"
#          else # Linux/macOS
#            ZIP_NAME="craterstats-$VERSION-${{ runner.os }}.zip"
#            zip -r dist/$ZIP_NAME dist/craterstats
#          fi       
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ env.ZIP_NAME }}

      - name: Create release on GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} dist/${{ env.ZIP_NAME }} --title "Release ${{ github.ref }}" --notes "Release notes for version ${{ github.ref }}"


