name: Build binaries

on:
  push:
    tags:
      - 'v*'  # on any tag push
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest] # macos-latest, ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # key based on requirements.txt
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pyinstaller
        run: |
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller craterstats.spec

      - name: Zip binary
        run: |
          # get version number from git tag (e.g., 'v3.3.3' -> '3.3.3')
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')

          if [ "${{ runner.os }}" == "Windows" ]; then
            ZIP_NAME="craterstats-$VERSION-win.zip"
            powershell -Command "Compress-Archive -Path dist\\craterstats -DestinationPath dist\\$ZIP_NAME"
          else # Linux/macOS
            if [ "${{ runner.os }}" == "Linux" ]; then
              ZIP_NAME="craterstats-$VERSION-linux-UNTESTED.zip"
            else
              ZIP_NAME="craterstats-$VERSION-macOS-UNTESTED.zip"
            fi
            cd dist
            zip -r $ZIP_NAME craterstats
            cd ..
          fi
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
        shell: bash  # also on Windows

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ env.ZIP_NAME }}

