name: Build Gallery

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/craterstats/config/demo_commands.txt'
      - 'scripts/make_gallery.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install setuptools        

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # Cache key based on requirements.txt
          restore-keys: |
            ${{ runner.os }}-pip-  

      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Install Craterstats
        run: |
          python setup.py install

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"          

      - name: Generate gallery.md and images
        run: |
          python scripts/make_gallery.py
          
          git add docs/gallery.md
          git commit -m "Build gallery.md" || echo "No changes to commit"
          git push origin main

      - name: List files after generating gallery
        run: |
          ls -R gallery/  

#      - name: Checkout gh-pages branch
#        uses: actions/checkout@v4
#        with:
#          ref: gh-pages

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages          

#      - name: Fetch main branch
#        run: |
#          git fetch origin main
#
#      - name: Copy images from main to gh-pages
#        run: |
#          git checkout origin/main -- gallery/demo/*

      - name: List files after generating gallery
        run: |
          ls -R gallery/

      - name: Commit and push changes to gh-pages
        run: |
          git add -A gallery/demo/*
          git commit -m "Deploy images to gh-pages" || echo "No changes to commit"
          git push origin gh-pages


