name: Build Gallery

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/craterstats/config/demo_commands.txt'
      - 'scripts/make_gallery.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # Cache key based on requirements.txt
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Install Craterstats
        run: |
          python setup.py install

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"          

      - name: Generate gallery.md and images in gh-pages
        run: |
          python scripts/make_gallery.py

          # Commit and push everything to gh-pages
          git add gallery/demo
          git commit -m "Generate gallery and images"
          git push origin gh-pages

      - name: Copy gallery.md to main
        run: |
          git checkout main
          git checkout gh-pages -- docs/gallery.md

          git add docs/gallery.md
          git commit -m "Build gallery.md"
          git push origin main
