name: Build gallery

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # key based on requirements.txt
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clean old deployment
        run: |
          git fetch --prune --unshallow                    
          git checkout --orphan gh-pages
          git rm -rf . || echo "No files to remove in gh-pages branch"
          git commit --allow-empty -m "Reset gh-pages deployment history" || echo "Nothing to commit"         
          git push origin gh-pages --force     # Force push to overwrite old deployments
          git checkout main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt
          python -m pip install coverage
      - name: Install Craterstats
        run: |
          python setup.py install
      - name: Run Tests with Coverage
        run: |
          coverage run -m unittest discover craterstats.tests -s src
          coverage report
      - name: Generate gallery images
        run: |
          python .github/make_gallery.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gallery
          publish_branch: gh-pages