name: Build Gallery

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/craterstats/config/demo_commands.txt'
      - 'scripts/make_gallery.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install setuptools        

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # Cache key based on requirements.txt
          restore-keys: |
            ${{ runner.os }}-pip-  

      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Install Craterstats
        run: |
          python setup.py install

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"          

      - name: Generate gallery.md and images
        run: |
          python scripts/make_gallery.py
          
          git add docs/gallery.md
          git commit -m "Build gallery.md" || echo "No changes to commit"
          git push origin main

      - name: List files after generating gallery
        run: |
          ls -R gallery/  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gallery
          publish_branch: gh-pages


